version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/worker"
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/evidence-app"
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 5
